CROP:
  crop: Maize
  cultivar: '900111'
  cultivar_file: 'D:/OneDrive - CGIAR/projects/suelos_honduras/dssat_files/MZCER048.CUL'

DATA:
  soil_datacube_path: ../tmp/hnd_soilgrids_data.nc
  climate_data_cube_path: ../tmp/climate_2020_2022_data_.nc
  vector_file: './data/tb_limitealdeas.shp'

PROCESS:
  country_level: 'id'
  aggregate_by: 'texture'
  pixel_level: False

MANAGEMENT:
  planting_date: '2021-06-01'
  harvesting_date: '2021-11-30'
  plantingWindow: 29
  fertilizer: False
  index_soilwat: 1
  crop: Maize
  cultivar: '900111'
  template: 'D:/OneDrive - CGIAR/projects/suelos_honduras/dssat_files/KEAG8104.MZX'

GENERAL:
  country: Honduras
  crop_model: DSSAT
  working_path: 'D:/OneDrive - CGIAR/scripts/agwise/tmp'
  use_r_for_exfile: True
  ncores: 10
  crs_reference: 'EPSG:4326'

ROI:
  path: "D:/OneDrive - CGIAR/projects/suelos_honduras/spatial_files/country/vector/tb_limitealdea_morethan100.shp"
  roi_column: id
  
WEATHER:
  paths:
    precipitation: "D:/OneDrive - CGIAR/projects/suelos_honduras/spatial_files/raster/weather/precipitation_hnd_raw"
    srad: "D:/OneDrive - CGIAR/projects/suelos_honduras/spatial_files/raster/weather/solar_radiation_hnd_raw"
    tmax: "D:/OneDrive - CGIAR/projects/suelos_honduras/spatial_files/raster/weather/temperature_tmax_hnd_raw"
    tmin: "D:/OneDrive - CGIAR/projects/suelos_honduras/spatial_files/raster/weather/temperature_tmin_hnd_raw"
  scale_factor: 10
  starting_date: '2020-01-01'
  ending_date: '2022-12-31'
  reference_variable: 'precipitation'

SOIL:
  path: "D:/OneDrive - CGIAR/projects/suelos_honduras/spatial_files/raster/soil/hnd"
  variables: ["bdod","cfvo", "clay", "nitrogen","phh2o", "sand", "silt", "soc","wv0010","cec", "wv0033", "wv1500"]
  depths: ["0-5","5-15","15-30","30-60"]
  crs_reference: 'ESRI:54052'
  reference_variable: sand
  depth_reference: '0-5'

SPATIAL_INFO:
  boundaries: "data/country.shp"
  crs: 'ESRI:54052'
  engine: "netcdf4"
