

SPATIAL_INFO:
  boundaries: "data/country.shp"
  crs: 'ESRI:54052'

SOIL:
  variables: ["wv0010","wv0033", "wv1500"]
  #variables: ["clay",  "sand", "silt", "wv0010","cec", "wv0033", "wv1500"]
  depths: ["0-5","5-15","15-30","30-60"]
  mission: soilgrids

GENERAL:
  suffix: 'hnd'
  task: download

PATHS:
  output_path: "soil/"

