DATES:
  starting_date: "2001-01-01"
  ending_date: "2001-12-31"

WEATHER:
  variables:
    precipitation:
      mission: chirps
      source: chips

    solar_radiation: 
      mission: agera5
      source: agera5

    temperature_tmax:
      mission: agera5
      source: agera5

    temperature_tmin:
      mission: agera5
      source: agera5
    
    relative_humidity:
      mission: agera5
      source: agera5
      time: "12_00"

SPATIAL_INFO:
  spatial_file: 'data/country.shp'
  extent: [-90, 12, -83, 17]

GENERAL:
  suffix: 'hnd'
  export_as_netcdf: True
  ncores: 10

PATHS:
  output_path: "weather/"

