DATES:
  starting_date: "1990-01-01"
  ending_date: "2024-12-31"

WEATHER:
  variables:
    solar_radiation: 
      mission: agera5
      source: agera5

    temperature_tmax:
      mission: agera5
      source: agera5

    temperature_tmin:
      mission: agera5
      source: agera5

    vapour_pressure:
      mission: agera5
      source: agera5

    wind_speed:
      mission: agera5
      source: agera5

SPATIAL_INFO:
  spatial_file: 'data/country.shp'
  extent: [-90, 12, -83, 17]

GENERAL:
  suffix: 'hnd'
  export_as_netcdf: True
  ncores: 10
  version: '2_0'

PATHS:
  output_path: "weather/"